### ISSUE TITLE
getting transactions and state of the accounts

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/js-ethereum-libp2p#5]
@wanderer, I'm not getting to see any Tx coming on the `beforeBlock` and the `afterBlock` only returns an object with empty values. `beforeTx` and `afterTx` never fires, but I guess that is natural since we are not issuing transactions.

I guess I can take the real transactions from the block itself. Is there a way to see "what accounts do I know and what balance do these accounts have"?

**Comment by wanderer** [comment]
should be fixed now

**Comment by daviddias** [comment]
yep, thank you! :)
